name: quiet
description: a music player

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: ^4.3.0
  dio_cookie_manager: 2.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  intl: ^0.17.0
  sembast: ^3.1.0+2
  scoped_model: ^2.0.0-nullsafety.0
  loader:
    git:
      url: https://github.com/boyan01/loader.git
      ref: e1ef2d9957bc8615c7f19f989d4fcfc142e20e93
  encrypt: ^5.0.0
  overlay_support: ^1.2.1
  music_player:
    git:
      url: https://github.com/boyan01/flutter-music-player.git
      ref: 7ba0513153853f769e3789b37f9ef630c85740f6
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  hive: ^2.0.4
  flutter_hooks: ^0.18.0
  equatable: ^2.0.3
  netease_api:
    path: netease_api/
  path: ^1.8.0
  async: ^2.8.0
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  dart_vlc: ^0.1.8
  collection: ^1.15.0
  window_manager: ^0.2.1
  lpinyin: ^2.0.3
  stream_transform: ^2.0.0
  windows_taskbar: ^1.0.0
  filesize: ^2.0.1
  desktop_drop: ^0.3.0
  dotted_border: ^2.0.0+2
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^6.0.1
  flutter_lints: ^2.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
