name: quiet
description: a music player

version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: ^4.3.0
  dio_cookie_manager: 2.0.0
  path_provider: ^2.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  intl: ^0.17.0
  scoped_model: ^2.0.0
  loader:
    git:
      url: https://github.com/boyan01/loader.git
      ref: e1ef2d9957bc8615c7f19f989d4fcfc142e20e93
  encrypt: ^5.0.0
  overlay_support: ^2.0.1
  music_player:
    git:
      url: https://github.com/boyan01/flutter-music-player.git
      ref: 19e2b5ee6a1327f5a599edfe10f6d4207bc4102b
  scrollable_positioned_list: ^0.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.18.0
  equatable: ^2.0.3
  netease_api:
    path: netease_api/
  path: ^1.8.0
  async: ^2.9.0
  riverpod: ^2.0.2
  flutter_riverpod: ^2.0.2
  hooks_riverpod: ^2.0.2
  collection: ^1.15.0
  window_manager: ^0.2.7
  lpinyin: ^2.0.3
  stream_transform: ^2.0.0
  windows_taskbar: ^1.0.0
  filesize: ^2.0.1
  desktop_drop: ^0.3.0
  dotted_border: ^2.0.0+2
  meta: ^1.7.0
  lychee_player: ^0.3.4
  fluentui_system_icons: ^1.1.182
  pretty_qr_code: ^2.0.2
  mixin_logger: ^0.0.1
  synchronized: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
