name: quiet
description: a music player

version: 0.4.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.3.0
  dio_cookie_manager: ^2.1.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  intl: ^0.18.0
  scoped_model: ^2.0.0
  loader:
    git:
      url: https://github.com/boyan01/loader.git
      ref: e1ef2d9957bc8615c7f19f989d4fcfc142e20e93
  encrypt: ^5.0.3
  overlay_support: ^2.1.0
  music_player:
    git:
      url: https://github.com/boyan01/flutter-music-player.git
      ref: f7a97ae6b892c133c63a10e5f8879a611520d3c7
  scrollable_positioned_list: ^0.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.18.0
  equatable: ^2.0.3
  netease_api:
    path: netease_api/
  path: ^1.8.0
  async: ^2.9.0
  riverpod: ^2.4.0
  flutter_riverpod: ^2.4.3
  hooks_riverpod: ^2.4.0
  collection: ^1.17.0
  window_manager: ^0.3.6
  lpinyin: ^2.0.3
  stream_transform: ^2.0.1
  windows_taskbar: ^1.1.2
  filesize: ^2.0.1
  desktop_drop:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 334939d7b6aebdf45881730a21731215976639ca
      path: packages/desktop_drop
  dotted_border: ^2.0.0+2
  meta: ^1.7.0
  lychee_player: ^0.4.0
  fluentui_system_icons: ^1.1.215
  mixin_logger: ^0.0.6
  synchronized: ^3.1.0
  ui_device:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      ref: 00654e51f51aa65cdc39784a3075c9abb8b9dd7c
      path: packages/ui_device
  qr_flutter: ^4.1.0
  system_clock: ^2.0.0
  handy_window: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.0

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
