name: netease_api
description: the api wrapper of netease cloud music
version: 0.0.1
homepage: https://github.com/boyan01/flutter-netease-music

publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^3.0.1
  dio_cookie_manager: ^2.1.1
  netease_music_api:
    #    path: ../../NeteaseCloudMusicApi
    git:
      url: https://github.com/boyan01/NeteaseCloudMusicApi.git
      ref: 47684bc8b75bf37ad3201993a9e3db0b5fe64ec3
  json_annotation: ^4.3.0
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1


